//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestSellingSubCategory
    {
        public Nullable<int> NumberOfSales { get; set; }
        public int SubCategoryID { get; set; }
    }
}
