//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMessage
    {
        public int MessageID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string MessageSubject { get; set; }
        public string CustomerMessage { get; set; }
    }
}
