//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShoppingSystemDBForWEBEntities : DbContext
    {
        public OnlineShoppingSystemDBForWEBEntities()
            : base("name=OnlineShoppingSystemDBForWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartItem> CartItem { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ContactMessage> ContactMessage { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerInformation> CustomerInformation { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceProducts> InvoiceProducts { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductComment> ProductComment { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<BestCustomer> BestCustomer { get; set; }
        public virtual DbSet<BestDiscountedProduct> BestDiscountedProduct { get; set; }
        public virtual DbSet<BestSellingCategory> BestSellingCategory { get; set; }
        public virtual DbSet<BestSellingSubCategory> BestSellingSubCategory { get; set; }
        public virtual DbSet<CategoryWithSubCategory> CategoryWithSubCategory { get; set; }
        public virtual DbSet<CustomerWithInformation> CustomerWithInformation { get; set; }
        public virtual DbSet<CustomerWithoutShopping> CustomerWithoutShopping { get; set; }
        public virtual DbSet<CustomerWithShopping> CustomerWithShopping { get; set; }
        public virtual DbSet<HighestStarproduct> HighestStarproduct { get; set; }
        public virtual DbSet<NewProduct> NewProduct { get; set; }
        public virtual DbSet<ProductsWithLowStock> ProductsWithLowStock { get; set; }
        public virtual DbSet<ProductWithBestSelling> ProductWithBestSelling { get; set; }
        public virtual DbSet<ProductWithCategoriesAndSubCategories> ProductWithCategoriesAndSubCategories { get; set; }
        public virtual DbSet<ProductWithLeastSelling> ProductWithLeastSelling { get; set; }
    }
}
