//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComment
    {
        public int ProductCommentID { get; set; }
        public int ProductID { get; set; }
        public string Comment { get; set; }
        public int ProductStar { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
    }
}
